### ISSUE TITLE
Making JDBC connection read-only

### ISSUE THREAD

**Issue by gouline** [AlexR2D2/metabase_duckdb_driver#9]
Would anyone be against making the JDBC connection read-only? From what I understand, Metabase only executes select statements, so it doesn't need write permissions to DuckDB files.

The benefit of a read-only connection is being able to insert data into the file externally (e.g. custom script, dbt transformations) and syncing Metabase without having to restart it. Makes it a powerful tool for local data analysis on your machine.

This [page](https://duckdb.org/docs/api/java.html#startup--shutdown) has a Java example:

```java
Properties ro_prop = new Properties();
ro_prop.setProperty("duckdb.read_only", "true");
Connection conn_ro = DriverManager.getConnection("jdbc:duckdb:/tmp/my_database", ro_prop);
```

Happy to figure out how to do it in Clojure and contribute a pull request, just wanted to ask first.

**Comment by AlexR2D2** [comment]
If someone will be against it is possible to add read_only parameters to the DuckDB config page (like [database_file](https://github.com/AlexR2D2/metabase_duckdb_driver/blob/66d4665e9095da684bca13498d30592a4fd92eff/resources/metabase-plugin.yaml#L14)). 

Also, if user wants to open database in the memory mode, for example just to read  parquet files (without native DuckDB database) then read_mode must be false, because DuckDB can't open im-memory DB in read only mode. So, i think we need some kind of check if trim of database_file param is empty then force read_only to false.
